[package]
name = "mines6d"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "*"
ndarray = "0.15.3"
rand = "0.8.4"
directories = "3.0"
